name: Save Eagler Docker Image

on:
  workflow_dispatch:

jobs:
  save-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: |
          docker pull qwedfrnhgef/eagler
      - name: Save Docker image to tar
        run: |
          docker save qwedfrnhgef/eagler -o eagler.tar
      - name: Upload image tarball as artifact
        uses: actions/upload-artifact@v3
        with:
          name: eagler-image
          path: eagler.tar
